name: ems
description: Event Management System Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  firebase_storage: ^10.3.11
  provider: ^6.0.3
  get_it: ^7.2.0
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  circular_clip_route: ^0.2.0+3
  animated_bottom_navigation_bar: ^1.1.0
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: GemunuLibre
      fonts:
        - asset: assets/fonts/GemunuLibre-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: AppIcons
      fonts:
        - asset: assets/icons/icons.ttf
